apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: frontend-ms 
        image: argocdpoc4545.azurecr.io/frontend-ms:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://backend.amanpathakdevops.study/api/tasks"
        ports:
        - containerPort: 3000
